apiVersion: batch/v1
kind: CronJob
metadata:
  name: call-endpoint
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: call-endpoint
              image: appropriate/curl
              args:
                - curl
                - -X
                - 'GET'
                - 'http://kubernetes.docker.internal:30002/UpdateCache'
          restartPolicy: OnFailure