apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary-api
  labels:
    app: dictionary-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary-api
  template:
    metadata:
      name: dictionary-api
      labels:
        app: dictionary-api
    spec:
      volumes:
        - name: dictionary-logs-storage
          hostPath:
            path: /data
            type: DirectoryOrCreate
      containers:
        - name: dictionary-api
          image: 62136/dictionary:latest
          imagePullPolicy: Always
          env:
            - name: ConnectionStrings__MySqlConnection
              value: "Server=postgres-service:5432;Database=Inventory;User Id=postgres;Password=1234;"
            - name: ConnectionStrings__RedisConnection
              value: "redis-service:6379"
            - name: Logging__LogFolderPath
              value: ""
          ports:
            - containerPort: 80
          volumeMounts:
            - name: dictionary-logs-storage
              mountPath: /dictionary-logs
  
---

apiVersion: v1
kind: Service
metadata:
  name: dictionary-service
spec:
  type: NodePort
  selector:
    app: dictionary-api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002